server:
  port: 8080
  max-http-header-size: 10240

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jta:
    atomikos:
      properties:
        max-actives: -1

mybatis-plus:
  typeAliasesPackage: cn.stylefeng.guns.modular.system.model,cn.stylefeng.guns.modular.entity
  mapper-locations:
    - classpath*:cn/stylefeng/guns/**/mapping/*.xml

log:
  path: _app_logs

logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace

    1. 先添加pom文件
    使用gradle :
    compile group: 'commons-net', name: 'commons-net', version: "3.6"

    2. 在application.yml中配置参数：
    ftp.host: localhost
    ftp.port: 210
    ftp.username: ftp01
    ftp.password: abc
    ftp.filepath: /

