server:
  port: 8080
  max-http-header-size: 10240

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jta:
    atomikos:
      properties:
        max-actives: -1

mybatis-plus:
  typeAliasesPackage: cn.stylefeng.guns.modular.system.model,cn.stylefeng.guns.modular.entity
  mapper-locations:
    - classpath*:cn/stylefeng/guns/**/mapping/*.xml

log:
  path: _app_logs

logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace

#支付宝 银商ftp
ftp.zfb.hostname=192.168.1.30
ftp.zfb.port=21
ftp.zfb.username=koolpos
ftp.zfb.password=koolpos401ftp
ftp.zfb.path=/ftp/images/old

#微信 中百ftp
ftp.wx.hostname=192.168.1.30
ftp.wx.port=21
ftp.wx.username=koolpos
ftp.wx.password=koolpos401ftp
ftp.wx.path=/ftp/images/old

#云闪付 银联ftp
ftp.ysf.hostname=192.168.1.30
ftp.ysf.port=21
ftp.ysf.username=koolpos
ftp.ysf.password=koolpos401ftp
ftp.ysf.path=/ftp/images/old

#中百富基 ftp
ftp.erp.hostname=192.168.1.30
ftp.erp.port=21
ftp.erp.username=koolpos
ftp.erp.password=koolpos401ftp
ftp.erp.path=/ftp/images/old

